export const HANGAR_QUIPS = [
  // Welcome and return
  "Welcome aboard, {pilot}",
  "Welcome back, {pilot}",
  "Good to see you, {pilot}",
  "The hangar missed you, {pilot}",
  "Your seat is ready, {pilot}",
  "Back where you belong, {pilot}",
  "Operations welcomes you, {pilot}",
  "The ramp lights are on, {pilot}",
  "Another flying day, {pilot}",
  "Ready for departure, {pilot}",
  "Glad you made it, {pilot}",
  "The flight deck is yours, {pilot}",
  "Your next chapter is airborne, {pilot}",
  "The crew room is open, {pilot}",
  "airDash is standing by, {pilot}",
  "The line is yours today, {pilot}",
  "Welcome to the sharp end, {pilot}",
  "Time to make sky, {pilot}",
  "Your wings are on the board, {pilot}",
  "The hangar doors are open, {pilot}",

  // Dispatch and routes
  "Dispatch has a plan, {pilot}",
  "Dispatch is ready when you are, {pilot}",
  "Your next route is calling, {pilot}",
  "Pick a city pair, {pilot}",
  "The flight board is live, {pilot}",
  "A route is waiting, {pilot}",
  "Your paperwork is suspiciously ready, {pilot}",
  "Dispatch saved you a good one, {pilot}",
  "The schedule has ideas, {pilot}",
  "Choose your next horizon, {pilot}",
  "Find a route worth remembering, {pilot}",
  "The map is full of possibilities, {pilot}",
  "Your OFP is one click away, {pilot}",
  "Today needs a flight number, {pilot}",
  "The timetable is feeling optimistic, {pilot}",
  "Your next leg starts here, {pilot}",
  "Point the nose somewhere new, {pilot}",
  "The route network is yours, {pilot}",
  "Time to connect two dots, {pilot}",
  "Give dispatch something to track, {pilot}",

  // A220 energy
  "Your A220 is waiting, {pilot}",
  "Another excellent A220 day, {pilot}",
  "The geared fans are ready, {pilot}",
  "Your flight deck has five screens, {pilot}",
  "The A220 wants a destination, {pilot}",
  "Small jet, big plans, {pilot}",
  "The ramp saved an A220 for you, {pilot}",
  "Your sidestick awaits, {pilot}",
  "The PW1500Gs are feeling eager, {pilot}",
  "Today's forecast calls for A220, {pilot}",
  "The flight controls say hello, {pilot}",
  "Your glass cockpit is glowing, {pilot}",
  "The quietest roar is yours, {pilot}",
  "Let the geared turbofans sing, {pilot}",
  "The A220 looks good on you, {pilot}",
  "Your favorite narrowbody checked in, {pilot}",
  "The avionics are awake, {pilot}",
  "The A220 brought its good manners, {pilot}",
  "Modern airliner energy, {pilot}",
  "That A220 will not fly itself, {pilot}",

  // Gates and ramp
  "The gate is yours, {pilot}",
  "Ground crew is standing by, {pilot}",
  "The jet bridge can wait, {pilot}",
  "Pushback is only a plan away, {pilot}",
  "The ramp is ready for you, {pilot}",
  "Bags loaded, dreams pending, {pilot}",
  "Chocks are in for now, {pilot}",
  "The tug driver knows your name, {pilot}",
  "Your departure gate is calling, {pilot}",
  "The marshaller has excellent vibes, {pilot}",
  "Beacon on when ready, {pilot}",
  "The GPU is humming, {pilot}",
  "Boarding can begin anytime, {pilot}",
  "The cabin door is still open, {pilot}",
  "Your stand is looking unusually tidy, {pilot}",
  "The ramp agents placed bets, {pilot}",
  "Push when the checklist says so, {pilot}",
  "Clear left, clear right, {pilot}",
  "The cones are perfectly aligned, {pilot}",
  "Your ground crew brought snacks, {pilot}",

  // Weather and operations
  "Check the weather, then send it, {pilot}",
  "Blue skies are optional, {pilot}",
  "The winds are negotiable, {pilot}",
  "Today has excellent visibility, {pilot}",
  "The METAR has opinions, {pilot}",
  "The clouds left room for you, {pilot}",
  "Crosswind practice is still practice, {pilot}",
  "Smooth air is never guaranteed, {pilot}",
  "The altimeter is waiting, {pilot}",
  "Mind the density altitude, {pilot}",
  "Today's ceiling looks promising, {pilot}",
  "The radar is painting possibilities, {pilot}",
  "Bring an alternate, {pilot}",
  "The winds aloft know the shortcut, {pilot}",
  "Conditions are within your style, {pilot}",
  "The weather desk says maybe, {pilot}",
  "The sky has variables, {pilot}",
  "Keep the shiny side up, {pilot}",
  "Plan for weather, fly the airplane, {pilot}",
  "The atmosphere noticed you logged in, {pilot}",

  // Streaks and experience
  "Keep that streak warm, {pilot}",
  "Your XP is cleared to climb, {pilot}",
  "Another day, another streak, {pilot}",
  "The flame needs a flight, {pilot}",
  "Continuity starts at the last arrival, {pilot}",
  "Your next origin already knows you, {pilot}",
  "Chain the route, {pilot}",
  "Three days makes it spicy, {pilot}",
  "The XP meter is listening, {pilot}",
  "Build momentum one leg at a time, {pilot}",
  "Yesterday's destination is today's start, {pilot}",
  "Keep the route chain alive, {pilot}",
  "Your streak has runway remaining, {pilot}",
  "A little bonus never hurt, {pilot}",
  "Make the next landing count, {pilot}",
  "Your level bar could use this, {pilot}",
  "Stay hot, fly smart, {pilot}",
  "The streak flame is watching, {pilot}",
  "Progress begins at pushback, {pilot}",
  "Add one more link to the chain, {pilot}",

  // Missions and exploration
  "A mission has your name on it, {pilot}",
  "The bonus route looks tempting, {pilot}",
  "New destination energy, {pilot}",
  "The mission board refreshed for you, {pilot}",
  "Go somewhere your logbook has not, {pilot}",
  "A multiplier is waiting, {pilot}",
  "The clock is ticking on a good route, {pilot}",
  "Chase the bonus, not the timer, {pilot}",
  "Your next mission just landed, {pilot}",
  "Make the network healthier, {pilot}",
  "One more city for the map, {pilot}",
  "The mission aircraft is ready, {pilot}",
  "Try a route with a little mystery, {pilot}",
  "Today's challenge is airborne, {pilot}",
  "A fresh destination awaits, {pilot}",
  "The map has an unopened corner, {pilot}",
  "Missions favor the decisive, {pilot}",
  "Your logbook wants variety, {pilot}",
  "The next bonus is not earning itself, {pilot}",
  "Choose the interesting route, {pilot}",

  // Flight-deck details
  "Set standard when cleared, {pilot}",
  "Positive rate, positive mood, {pilot}",
  "V-speeds before vibes, {pilot}",
  "Trim set, route set, {pilot}",
  "The FMS is ready for diplomacy, {pilot}",
  "LNAV has entered the chat, {pilot}",
  "VNAV would like a word, {pilot}",
  "Check thrust, then trust, {pilot}",
  "Your top of descent is out there, {pilot}",
  "Direct-to adventure, {pilot}",
  "The magenta line looks convincing, {pilot}",
  "Squawk confidence, {pilot}",
  "Cleared as filed-ish, {pilot}",
  "The autopilot brought boundaries, {pilot}",
  "Manage the energy, {pilot}",
  "Flaps are a future problem, {pilot}",
  "The glidepath is feeling centered, {pilot}",
  "Minimums are not suggestions, {pilot}",
  "Stable by one thousand, {pilot}",
  "Grease it or log it anyway, {pilot}",

  // Calm cockpit
  "Coffee secured, checklist open, {pilot}",
  "No rush, just good decisions, {pilot}",
  "Calm cockpit, sharp flying, {pilot}",
  "Take the good runway, {pilot}",
  "The sky is not going anywhere, {pilot}",
  "Fly the plan you briefed, {pilot}",
  "A clean flight starts here, {pilot}",
  "Tiny switches, large consequences, {pilot}",
  "Make future you proud, {pilot}",
  "The logbook has an empty line, {pilot}",
  "Your headset looks professional, {pilot}",
  "The seatbelt sign believes in you, {pilot}",
  "Today is a good day to taxi slowly, {pilot}",
  "One checklist at a time, {pilot}",
  "The cockpit is a no-drama zone, {pilot}",
  "Precision is a personality, {pilot}",
  "You brought the pilot energy, {pilot}",
  "Let the passengers rate the landing, {pilot}",
  "The runway is expecting you, {pilot}",
  "Make it smooth enough, {pilot}",

  // Hubs and network
  "Atlanta is on the board, {pilot}",
  "Denver has room for you, {pilot}",
  "Santo Domingo is calling, {pilot}",
  "Spokane sees you, {pilot}",
  "The network needs your next leg, {pilot}",
  "Move an airframe, move the airline, {pilot}",
  "Every arrival reshapes the map, {pilot}",
  "Position the fleet wisely, {pilot}",
  "Your destination becomes opportunity, {pilot}",
  "Keep the hubs connected, {pilot}",
  "A parked A220 needs purpose, {pilot}",
  "The route map could use your signature, {pilot}",
  "Pick a hub and make some noise, {pilot}",
  "The fleet goes where you take it, {pilot}",
  "One flight can fix the balance, {pilot}",
  "The network is better airborne, {pilot}",
  "Your next arrival changes everything, {pilot}",
  "Connect the bases, {pilot}",
  "Leave the aircraft somewhere useful, {pilot}",
  "airDash moves when you do, {pilot}",
] as const

export function pickHangarQuip(pilot: string, random: () => number = Math.random): string {
  const sample = Math.max(0, Math.min(0.999999999, random()))
  const template = HANGAR_QUIPS[Math.floor(sample * HANGAR_QUIPS.length)]
  return template.replaceAll("{pilot}", pilot)
}
