export interface DiscordUser { id: string; username: string; displayName: string; avatar: string }
export interface Application { id: number; preferred_name: string; vatsim_cid: string; base_code: string; simulator: string; experience: string; introduction: string; status: string; reviewer_notes: string; submitted_at: string }
export interface StreakSummary { flightDays: { current: number; best: number; lastFlightDate: string | null; bonusPercent: number }; continuity: { current: number; best: number; lastDestination: string | null } }
export interface Pilot { discord_id: string; pilot_number: string; display_name: string; vatsim_cid: string; base_code: string; status: string; rank_name?: string; leadership_title?: string | null; profile_image_url?: string | null; avatar_url?: string | null; pronouns?: string; about_me?: string; total_block_minutes: number; experience?: number; missions_completed?: number; assignments_completed?: number; simbrief_username?: string | null; total_flights: number; joined_at: string; streaks?: StreakSummary }
export type PublicPilot = Pick<Pilot, "discord_id" | "pilot_number" | "display_name" | "base_code" | "rank_name" | "leadership_title" | "profile_image_url" | "avatar_url" | "total_flights" | "total_block_minutes" | "joined_at" | "streaks">
export interface SimBriefPlan { sourceUrl: string; format: string; origin: string; destination: string; alternate: string | null; route: string; cruiseAltitude: number | null; costIndex: number | null; aircraftIcao: string; airlineIcao?: string | null; flightNumber?: string | null; callsign?: string | null; commercialDesignator?: string | null; commercialFlightNumber?: string | null; scheduledOut: string | null; scheduledIn: string | null; blockFuel: number | null; tripFuel: number | null; endurance: number | null; units: string; passengers: number | null; cargo: number | null; atcFlightPlan: string }
export type PirepOutcome = "COMPLETED" | "DIVERTED" | "INCOMPLETE"
export interface VolantaFlight { sourceUrl: string; flightId: string; state: string | null; origin: string | null; destination: string | null; alternate: string | null; aircraftIcao: string | null; aircraftRegistration: string | null; aircraftTitle: string | null; callsign: string | null; flightNumber: string | null; network: string | null; actualOutAt: string | null; actualOffAt: string | null; actualOnAt: string | null; actualInAt: string | null; reportEndAt: string | null; arrivalVerified: boolean; simBlockSeconds: number | null; realBlockSeconds: number | null; timeCompressionRatio: number; timeCompressionDetected: boolean; landingRate: number | null; distanceNm: number | null; plannedDistance: number | null; fuelBurn: number | null; positionCount: number; finalPosition: { latitude: number | null; longitude: number | null; altitude: number | null; onGround: boolean; time: string | null } | null; simulator: string | null; hasDiverted: boolean; diversionAirportIcao: string | null; diversionReason: string | null }
export interface FlightOutcomeAnalysis { reportable: boolean; reportEndAt: string | null; outcome: PirepOutcome; requiresReason: boolean; creditMultiplier: number; origin: string | null; destination: string | null; alternate: string | null; actualDestination: string | null; repositionAirport: string | null; repositionMethod: string; progressRatio: number | null; decisionPointReached: boolean; hasDiversionEvidence: boolean; diversionAirport: string | null; suggestedReason: string | null; arrivalVerified: boolean; providerState: string | null }
export interface Assignment { id: number; route_id: number; flight_number: number; origin: string; destination: string; block_minutes: number; registration: string; flight_date: string; status: string; source?: "BOARD" | "MISSION" | "SCHEDULE"; mission_type?: "STANDARD" | "RECOVERY"; recovery_of_assignment_id?: number | null; booked_at: string; started_at?: string | null; expires_at: string; departure_gate?: string | null; arrival_gate?: string | null; tail_number?: string | null; simbrief_url?: string | null; simbrief_format?: string | null; flight_plan?: SimBriefPlan | null; cancelled_at?: string | null; cancelled_by?: string | null; cancellation_code?: string | null; cancellation_reason?: string | null }
export interface Aircraft { registration: string; fleet_number: number; aircraft_type: string; status: string; status_reason?: string | null; status_until?: string | null; current_airport: string; current_gate?: string | null; livery_url: string | null; livery_sha256: string | null; livery_msfs2020_url?: string | null; livery_msfs2020_sha256?: string | null; livery_name?: string | null; special_livery?: boolean; thumbnail_url?: string | null; total_block_minutes: number; total_cycles: number; livery_download_count?: number; livery_msfs2020_download_count?: number }
export interface OrgUpdate { id: number; kind: string; title: string; body: string; is_public?: boolean; slug?: string | null; summary?: string; hero_image_url?: string | null; author_name?: string; published_at?: string | null; pilot_discord_id?: string | null; pilot_name?: string | null; pilot_number?: string | null; aircraft_registration?: string | null; registration?: string | null; created_by?: string | null; created_by_name?: string | null; created_at: string }
export interface Route { id: number; flight_number: number; origin: string; destination: string; block_minutes: number; days: string; available_aircraft?: string[] }
export interface MeResponse { user: DiscordUser; isOwner: boolean; application: Application | null; pilot: Pilot | null; assignment: Assignment | null; lastFlightAt?: string | null; downloadedLiveries?: string[]; downloadedLiveryVersions?: Array<{ registration: string; simulator: "MSFS2020" | "MSFS2024" }>; streaks?: StreakSummary }
export interface Base { code: string; name: string; lat: number; lon: number; role: string; is_active?: boolean; sort_order?: number; pilot_count?: number }
export interface NewsRelease { id: number; kind: string; title: string; summary: string; body?: string; slug: string; hero_image_url?: string | null; author_name: string; published_at: string }
export interface PublicResponse { aircraft: Aircraft[]; routes: Route[]; bases: Base[]; pilots?: PublicPilot[]; topPilot?: { discord_id: string; display_name: string; total_block_minutes: number } | null }
export interface AdminOverview { applications: Array<Application & { discord_id: string; username: string; avatar_url: string }>; pireps: Array<Record<string, unknown>>; pilots: Pilot[]; assignments: Array<Assignment & { pilot_name?: string; pilot_username?: string; cancelled_by_name?: string | null; cancelled_by_username?: string | null }>; aircraft: Array<Aircraft & { status_reason?: string | null; status_until?: string | null }>; audit: Array<Record<string, unknown>>; visitors?: Array<{ discord_id: string; username: string; display_name: string; avatar_url: string; last_login_at: string }>; orgUpdates?: OrgUpdate[]; settings?: { autoApprovePireps?: boolean }; bases?: Base[] }
